name: telegram_stickers_import
description: Telegram stickers importing Flutter plugin for iOS and Android
version: 1.0.1
homepage: https://github.com/otopba/telegram_stickers_import

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
  plugin:
    platforms:
      android:
        package: com.otopba.telegram_stickers_import
        pluginClass: TelegramStickersImportPlugin
      ios:
        pluginClass: TelegramStickersImportPlugin